// Serialize an analysis result to Markdown so it can leave the browser —
// into a doc, a ticket, an email or a PR description.

const DISCLAIMER =
  '_Generated by [RegReady](https://reg-ready.vercel.app). AI-generated analysis — not legal advice. Verify against the primary regulatory text._';

function list(items, bullet = '-') {
  if (!items?.length) return '';
  return items.map((i) => `${bullet} ${i}`).join('\n');
}

function section(heading, body) {
  return body ? `## ${heading}\n\n${body}\n` : '';
}

function translatorMarkdown(r) {
  const s = r.impactSummary || {};
  const parts = [`# Regulatory Impact — ${s.regulatorySource || 'Analysis'}\n`];

  if (s.headline) parts.push(`**${s.headline}**\n`);
  if (s.bullets?.length) parts.push(`${list(s.bullets)}\n`);
  if (s.affectedProducts?.length) {
    parts.push(section('Affected Products', list(s.affectedProducts)));
  }

  if (r.requirements?.length) {
    const rows = r.requirements
      .map((q) => {
        const lines = [
          `### ${q.id} — ${q.title}`,
          '',
          `**Priority:** ${q.priority}  `,
          `**Basis:** ${q.regulatoryBasis}  `,
          q.complianceDeadline ? `**Deadline:** ${q.complianceDeadline}  ` : '',
          q.affectedSystems?.length ? `**Systems:** ${q.affectedSystems.join(', ')}  ` : '',
          '',
          q.description || '',
        ];
        return lines.filter(Boolean).join('\n');
      })
      .join('\n\n');
    parts.push(section('Engineering Requirements', rows));
  }

  if (r.jiraTickets?.length) {
    const rows = r.jiraTickets
      .map((t) => {
        const ac = t.acceptanceCriteria?.length
          ? `\n\n**Acceptance criteria**\n${list(t.acceptanceCriteria)}`
          : '';
        const labels = t.labels?.length ? `\n\n\`${t.labels.join('` `')}\`` : '';
        return `### ${t.ticketId} — ${t.title}\n\n**Type:** ${t.type} · **Priority:** ${t.priority} · **Points:** ${t.storyPoints}\n\n${t.description || ''}${ac}${labels}`;
      })
      .join('\n\n');
    parts.push(section('Implementation Tickets', rows));
  }

  parts.push(downstreamSection(r.downstreamDependencies));
  parts.push(`\n---\n\n${DISCLAIMER}\n`);
  return parts.filter(Boolean).join('\n');
}

function riskScorerMarkdown(r) {
  const c = r.riskClassification || {};
  const parts = [`# Risk Assessment — ${c.tier || 'Unclassified'}\n`];

  if (c.confidence) parts.push(`**Confidence:** ${c.confidence}  `);
  if (c.euAiActBasis) parts.push(`**Basis:** ${c.euAiActBasis}\n`);
  if (c.justification) parts.push(`${c.justification}\n`);

  if (r.regulatoryExposure?.length) {
    const header =
      '| Regulation | Jurisdiction | Authority | Risk | Provisions | Penalty |\n|---|---|---|---|---|---|';
    const rows = r.regulatoryExposure
      .map((e) =>
        `| ${e.regulation || ''} | ${e.jurisdiction || ''} | ${e.bindingAuthority || ''} | ${e.riskLevel || ''} | ${(e.provisionsTriggered || []).join('; ')} | ${e.penaltyExposure || ''} |`,
      )
      .join('\n');
    parts.push(section('Regulatory Exposure', `${header}\n${rows}`));
  }

  if (r.vulnerabilityFlags?.length) {
    const rows = r.vulnerabilityFlags
      .map((f) => {
        const compounding = f.compoundingRisk ? `\n  - Compounding: ${f.compoundingRisk}` : '';
        return `- **[${f.severity}] ${f.category}** — ${f.description}\n  - Basis: ${f.regulatoryBasis}${compounding}`;
      })
      .join('\n');
    parts.push(section('Vulnerability Flags', rows));
  }

  if (r.recommendedActions?.length) {
    const rows = r.recommendedActions
      .map((a) => `- **${a.priority}** ${a.action}\n  - Why: ${a.rationale}\n  - Owner: ${a.owner} · Timeline: ${a.timeline}`)
      .join('\n');
    parts.push(section('Recommended Actions', rows));
  }

  if (r.monitoringIndicators?.length) {
    const rows = r.monitoringIndicators
      .map((m) => `- **${m.indicator}**\n  - Source: ${m.source}\n  - If it fires: ${m.triggerAction}`)
      .join('\n');
    parts.push(section('Monitoring Indicators', rows));
  }

  parts.push(downstreamSection(r.downstreamDependencies));

  const p = r.compliantPathSummary;
  if (p) {
    const blockers = p.criticalBlockers?.length
      ? `\n**Critical blockers**\n${list(p.criticalBlockers)}\n`
      : '';
    parts.push(
      section(
        'Compliant Path',
        `**Deployable as-is:** ${p.canBeDeployedAsIs}\n${blockers}\n${p.modifiedVersion || ''}`,
      ),
    );
  }

  parts.push(`\n---\n\n${DISCLAIMER}\n`);
  return parts.filter(Boolean).join('\n');
}

function saifMarkdown(r) {
  const ctx = r.regulatoryContext || {};
  const a = r.overallAssessment || {};
  const parts = [`# SAIF Coverage — ${ctx.regulation || 'Analysis'}\n`];

  if (ctx.jurisdiction) parts.push(`**Jurisdiction:** ${ctx.jurisdiction}  `);
  if (a.complianceReadiness !== undefined) {
    parts.push(`**SAIF coverage:** ${a.complianceReadiness}/100\n`);
  }
  if (ctx.coreObligation) parts.push(`${ctx.coreObligation}\n`);
  if (a.summary) parts.push(`${a.summary}\n`);
  if (a.strongestAlignment) parts.push(`**Strongest alignment:** ${a.strongestAlignment}\n`);
  if (a.criticalGaps?.length) parts.push(section('Critical Gaps', list(a.criticalGaps)));

  if (r.saifMapping?.length) {
    const rows = r.saifMapping
      .map((m) => {
        const controls = m.specificControls?.length
          ? `\n  - Controls: ${m.specificControls.join('; ')}`
          : '';
        const gaps = m.gaps?.length ? `\n  - Gaps: ${m.gaps.join('; ')}` : '';
        return `- **${m.element}. ${m.elementName} — ${m.coverage}**\n  - ${m.explanation}${controls}${gaps}`;
      })
      .join('\n');
    parts.push(section('SAIF Element Mapping', rows));
  }

  if (r.gapRecommendations?.length) {
    const rows = r.gapRecommendations
      .map((g) => {
        const target = g.saifElement ? `extends SAIF Element ${g.saifElement}` : 'new capability required';
        const notes = g.implementationNotes ? `\n  - Notes: ${g.implementationNotes}` : '';
        return `- **${g.priority}** ${g.gap}\n  - Recommendation: ${g.recommendation}\n  - Owner: ${g.owner} (${target})${notes}`;
      })
      .join('\n');
    parts.push(section('Gap Recommendations', rows));
  }

  if (r.crossFrameworkInsights?.length) {
    const rows = r.crossFrameworkInsights
      .map((i) => `- **${i.insight}**\n  - ${i.relevance}`)
      .join('\n');
    parts.push(section('Cross-Framework Insights', rows));
  }

  parts.push(`\n---\n\n${DISCLAIMER}\n`);
  return parts.filter(Boolean).join('\n');
}

function downstreamSection(deps) {
  if (!deps?.length) return '';
  const rows = deps
    .map((d) => `- **${d.article}** — ${d.obligation}\n  - ${d.relevance}`)
    .join('\n');
  return section('Downstream Dependencies', rows);
}

const SERIALIZERS = {
  translator: translatorMarkdown,
  riskScorer: riskScorerMarkdown,
  saif: saifMarkdown,
};

export function toMarkdown(mode, result) {
  const fn = SERIALIZERS[mode];
  if (!fn || !result) return '';
  return fn(result).replace(/\n{3,}/g, '\n\n').trim() + '\n';
}

export function filenameFor(mode, result) {
  const base = {
    translator: 'regready-requirements',
    riskScorer: 'regready-risk-assessment',
    saif: 'regready-saif-mapping',
  }[mode] || 'regready-analysis';

  const label =
    result?.impactSummary?.regulatorySource ||
    result?.regulatoryContext?.regulation ||
    result?.riskClassification?.tier ||
    '';

  const slug = label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40);

  return slug ? `${base}-${slug}` : base;
}

/**
 * Render one ticket in Jira wiki markup, ready to paste into a Jira
 * description field. Jira does not accept Markdown there, so the Markdown
 * export above is the wrong format for the one place these tickets are headed.
 */
export function toJiraMarkup(ticket) {
  if (!ticket) return '';
  const lines = [`h3. ${ticket.title || 'Untitled'}`, ''];

  const meta = [
    ticket.ticketId ? `*Ref:* ${ticket.ticketId}` : '',
    ticket.type ? `*Type:* ${ticket.type}` : '',
    ticket.priority ? `*Priority:* ${ticket.priority}` : '',
    ticket.storyPoints ? `*Points:* ${ticket.storyPoints}` : '',
  ].filter(Boolean);
  if (meta.length) lines.push(meta.join(' | '), '');

  if (ticket.description) lines.push(ticket.description, '');

  if (ticket.acceptanceCriteria?.length) {
    lines.push('h4. Acceptance criteria', '');
    for (const ac of ticket.acceptanceCriteria) lines.push(`* ${ac}`);
    lines.push('');
  }

  if (ticket.labels?.length) {
    lines.push(`*Labels:* ${ticket.labels.join(', ')}`, '');
  }

  lines.push('----', 'Generated by RegReady (https://reg-ready.vercel.app) — AI-generated, not legal advice.');
  return lines.join('\n');
}

/** CSV for Jira's external-system import. */
export function toJiraCsv(tickets) {
  if (!tickets?.length) return '';
  const cols = ['Summary', 'Issue Type', 'Priority', 'Description', 'Story Points', 'Labels'];
  const esc = (v) => `"${String(v ?? '').replace(/"/g, '""')}"`;

  const rows = tickets.map((t) => {
    const desc = [
      t.description || '',
      t.acceptanceCriteria?.length
        ? `\n\nAcceptance criteria:\n${t.acceptanceCriteria.map((a) => `* ${a}`).join('\n')}`
        : '',
      t.ticketId ? `\n\nRef: ${t.ticketId}` : '',
    ].join('');
    return [
      t.title || '',
      t.type || 'Task',
      t.priority || '',
      desc,
      t.storyPoints ?? '',
      (t.labels || []).join(' '),
    ].map(esc).join(',');
  });

  return [cols.map(esc).join(','), ...rows].join('\n');
}
